### ISSUE TITLE
Allow contributions by enabling publishing branches and pull requests.

### ISSUE THREAD

**Issue by benny-jon** [pdil/PDColorPicker#11]
### Expected behavior
- I would like to be able to publish new branches and create pull requests.

### Actual behavior
- I'm getting the current error:

> Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open preferences and verify that you're signed in with an account that has permission to access this repository.

### Steps to reproduce behavior
- Try to push a brach from GitHubDesktop

**Comment by pdil** [comment]
Did you fork the repo before creating a pull request?

If you fork the repo you will be able to make commits in your own copy of the repo and then create a pull request to merge the changes into the main one.

https://help.github.com/articles/creating-a-pull-request-from-a-fork/

Let me know if that still doesn't work. Thanks!

**Comment by benny-jon** [comment]
Oh, thanks for the clarification, will try that tonight.

**Comment by benny-jon** [comment]
This was actually my first time contributing to a repo in GitHub. Thanks a lot for the link. Exciting stuff.
