### ISSUE TITLE
Cannot override mutable property with read-only property 'state'

### ISSUE THREAD

**Issue by jayan-gsolc** [pdil/PDColorPicker#14]
### Expected behavior
can build properly in swift 4.2

### Actual behavior

Cannot override mutable property with read-only property 'state'

### Steps to reproduce behavior
pod install & after that build the project. 

===

* **Xcode version**: 10.0
* **iOS version**: 
* **Device(s)**:

**Comment by pdil** [comment]
@jayan-gsolc This has been fixed in v0.8.1 which now supports iOS 12 and Swift 4.2. If you run `pod update` on your project(s) it should now work.

https://github.com/pdil/PDColorPicker/releases/tag/0.8.1 for more info
